In [1]:
import pandas as pd
import numpy as np

In [2]:
customerData = pd.read_csv("../../../Python_Script/dataset/customerdata.csv")

In [3]:
customerData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
146  Z13534  3662.437527    3            6    0.900000        Early-bird
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[150 rows x 6 columns]

In [4]:
def productAge(productAge):
    
    if productAge < 1 :
        return 1
    elif productAge < 2 :
        return 2
    elif productAge < 3 :
        return 3
    else:
        return 4

In [5]:
customerData["product_new_age"] = customerData.PRODUCTAGE.apply(productAge)

In [6]:
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,product_new_age
0,A13566,4273.900000,3,6,1.679181,Big-Screen-lover,2
1,A14219,3642.441950,2,4,2.682023,Sleeping-dog,3
2,A15312,3653.884565,2,5,3.208202,Sleeping-dog,4
3,A16605,3713.211107,2,6,0.900000,Early-bird,1
4,B10634,3391.074215,2,4,2.453656,Sleeping-dog,3
...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2,5,2.463670,Big-Screen-lover,3
146,Z13534,3662.437527,3,6,0.900000,Early-bird,1
147,Z16428,3516.500000,2,5,2.371301,Big-Screen-lover,3
148,Z16735,3300.100000,2,5,1.704942,Big-Screen-lover,2
149,Z19835,3326.526183,2,6,1.200000,Early-bird,2